/* eslint-disable no-trailing-spaces */

const actionTypes = {
  HANDLE_SUCCESS_RESPONSE: 'HANDLE_SUCCESS_RESPONSE',
  HANDLE_ERROR_RESPONSE: 'HANDLE_ERROR_RESPONSE',
  SAVE_USER_CREDENTIALS: 'SAVE_USER_CREDENTIALS',
  SET_QUERIES: 'SET_QUERIES',
  CLEAR_QUERIES: 'CLEAR_QUERIES',
  SET_QUERY_DETAILS: 'SET_QUERY_DETAILS',
  SET_QUERY_RULES: 'SET_QUERY_RULES',
  CLEAR_QUERY_DATA: 'CLEAR_QUERY_DATA',
  CLEAR_QUERY_RULES: 'CLEAR_QUERY_RULES',
  HANDLE_USER_QUERIES: 'HANDLE_USER_QUERIES',
  ADD_QUERY_TO_QUERY_LIST: 'ADD_QUERY_TO_QUERY_LIST',
  REMOVE_QUERY_FROM_QUERY_LIST: 'REMOVE_QUERY_FROM_QUERY_LIST',
  UPDATE_QUERY_FROM_LIST: 'UPDATE_QUERY_FROM_LIST',
  SET_MODEL_FIELDS: 'SET_MODEL_FIELDS'
};


export default actionTypes
