/* eslint-disable no-trailing-spaces */

export const actionTypes = {
  HANDLE_SUCCESS_RESPONSE: 'HANDLE_SUCCESS_RESPONSE',
  HANDLE_ERROR_RESPONSE: 'HANDLE_ERROR_RESPONSE',
  SAVE_USER_CREDENTIALS: 'SAVE_USER_CREDENTIALS',
  SET_QUERIES: 'SET_QUERIES',
  CLEAR_QUERIES: 'CLEAR_QUERIES',
  SET_QUERY_DATA: 'SET_QUERY_DATA',
  CLEAR_QUERY_DATA: 'CLEAR_QUERY_DATA',
};
